version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    volumes:
      - ./build/db:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  app:
    build:
      dockerfile: build/app/Dockerfile
      context: .
    container_name: app
    command: bash -c "
      while !</dev/tcp/db/5432; do sleep 1;
      done; alembic upgrade head
      && uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - ./project:/usr/src/app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    env_file:
      - app.env
  nginx:
    build: build/nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app

volumes:
  db:
  app:
